### ISSUE TITLE
Schema Generation

### ISSUE THREAD

**Issue by adkapur** [real-logic/real-logic.github.io#1]
In the SBE repository, it was confirmed that real logic SBE implementation supports nested repeating groups. Does it also support creation of the XML schema? If so then could we please get access to the API?

**Comment by mjpt777** [comment]
Best if you ask in this repo.

https://github.com/real-logic/simple-binary-encoding

Can you provide more detail of what you mean by creation of the XML Schema. The SbeTool takes a schema and generates codec stubs or IR.
